#!/usr/bin/with-contenv bash

# nginx Path
NGINX_CONFIG=/etc/nginx/sites-available/default
HTML_FILE="/kclient/public/index.html"
HTML_FILE2="/usr/local/share/kasmvnc/www/index.html"
FILE1="/usr/local/share/kasmvnc/www/dist/functions.js"

UUID="${UUID}"
DEFAULT_IDLE_THRESHOLD=""
CUSTOM_DOMAIN=""

# user passed env vars
CPORT="${CUSTOM_PORT:-3000}"
CHPORT="${CUSTOM_HTTPS_PORT:-3001}"
CUSER="${CUSTOM_USER:-abc}"
SFOLDER="${SUBFOLDER:-/}"

# create self signed cert
if [ ! -f "/config/ssl/cert.pem" ]; then
  mkdir -p /config/ssl
  openssl req -new -x509 \
    -days 3650 -nodes \
    -out /config/ssl/cert.pem \
    -keyout /config/ssl/cert.key \
    -subj "/C=US/ST=CA/L=Carlsbad/O=Linuxserver.io/OU=LSIO Server/CN=*"
  chmod 600 /config/ssl/cert.key
  chown -R abc:abc /config/ssl
fi

# modify nginx config
cp /defaults/default.conf ${NGINX_CONFIG}
sed -i "s/3000/$CPORT/g" ${NGINX_CONFIG}
sed -i "s/3001/$CHPORT/g" ${NGINX_CONFIG}
sed -i "s|SUBFOLDER|$SFOLDER|g" ${NGINX_CONFIG}
sed -i "s|{{UUID}}|$UUID|g" $NGINX_CONFIG
sed -i "s|{{UUID}}|$UUID|g" $HTML_FILE
sed -i "s|{{UUID}}|$UUID|g" $HTML_FILE2
sed -i "s|{{UUID}}|$UUID|g" $FILE1
if [ ! -z ${DISABLE_IPV6+x} ]; then
  sed -i '/listen \[::\]/d' ${NGINX_CONFIG}
fi
chmod -R 755 /kclient
chown -R www-data:www-data /kclient
if [ ! -z ${PASSWORD+x} ]; then
  printf "${CUSER}:$(openssl passwd -apr1 ${PASSWORD})\n" > /etc/nginx/.htpasswd
  sed -i 's/#//g' ${NGINX_CONFIG}
fi