#!/bin/bash

google-chrome \
  --start-maximized \
  --no-first-run \
  --disable-session-crashed-bubble \
  --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
  --hide-crash-restore-bubble \
  --user-data-dir \
  --disable-dev-shm-usage \
   "$@" $FF_OPEN_URL > /dev/null 2>&1

PROCESS_NAME="google-chrome"


