# Generated by Django 6.0.6 on 2026-07-13 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_filename', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('requires_spot', models.BooleanField(default=False)),
                ('idle_timeout_override_minutes', models.PositiveIntegerField(blank=True, help_text='Override idle timeout for this browser type only.', null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='BrowserAvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.workspace')),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='browsers.browserimage')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('user__isnull', False), ('workspace__isnull', True)), models.Q(('group__isnull', False), ('user__isnull', True), ('workspace__isnull', True)), models.Q(('group__isnull', True), ('user__isnull', True), ('workspace__isnull', False)), _connector='OR'), name='exactly_one_subject')],
            },
        ),
    ]
