# Generated by Django 6.0.7 on 2026-07-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsers', '0002_populate_default_browsers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'browser categories',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='browserimage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='browsers', to='browsers.browsercategory'),
        ),
    ]
