# Generated by Django 6.0.7 on 2026-07-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='Auto-created personal workspace for this user'),
        ),
    ]
