# Generated by Django 6.0.7 on 2026-07-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsers', '0003_add_browser_categories'),
        ('workspaces', '0002_add_is_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='allowed_browsers',
            field=models.ManyToManyField(blank=True, related_name='workspace_allowlist', to='browsers.browserimage'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='max_session_duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
