# Generated by Django 6.0.7 on 2026-07-13 21:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_add_allowed_browsers_and_max_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
