# Generated by Django 6.0.7 on 2026-07-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_alter_workspacemembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='workspace_logos/'),
        ),
    ]
