# Generated by Django 6.0.6 on 2026-07-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_workspace_feature_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='enable_persistent_storage',
            field=models.BooleanField(default=False, help_text='Allow members of this workspace to use persistent S3 storage (requires global flag).'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='s3files_access_point_arn',
            field=models.CharField(blank=True, default='', help_text="ARN of the S3 Files access point for this workspace's persistent storage.", max_length=500),
        ),
    ]
