# Generated by Django 6.0.6 on 2026-07-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workspace_enable_persistent_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='member', max_length=20),
        ),
    ]
