"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import re

def str_to_bool(val):
    val = str(val).strip().lower()
    return val in ('true', '1', 'yes')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DOT_ENV_PATH = BASE_DIR / ".env"

if DOT_ENV_PATH.exists():
    load_dotenv(DOT_ENV_PATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', os.environ.get('SECRET_KEY', 'django-insecure-xq1rhglk0+4r@x9=sqv*ah7@d#5yq_v1md!0rzsrh2^+u+xyaw'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str_to_bool(os.environ.get('DEBUG', 'False'))

# DEV_MODE bypasses all AWS ECS and Cloudflare calls so the app can be tested
# locally without real infrastructure.  Sessions are immediately "activated"
# with fake metadata.  Never enable this in production.
DEV_MODE = str_to_bool(os.environ.get('DEV_MODE', 'False'))

if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise RuntimeError('Set a real SECRET_KEY in production (current value is the insecure default)')

CUSTOM_DOMAIN = os.environ.get('CUSTOM_DOMAIN', os.environ.get('DOMAIN', ''))
_custom_host = CUSTOM_DOMAIN.split(':')[0] if CUSTOM_DOMAIN else ''

DEPLOYMENT_MODE = os.environ.get('DEPLOYMENT_MODE', 'proxy')
BASIC_MODE = DEPLOYMENT_MODE == 'basic'

raw_hosts = os.environ.get('ALLOWED_HOSTS', '')

_base_hosts = ['127.0.0.1', 'localhost', '0.0.0.0', 'django', 'backend', 'ovb-backend', 'host.docker.internal']
if _custom_host:
    _base_hosts.append(_custom_host)

if raw_hosts.strip():
    ALLOWED_HOSTS = [h.strip() for h in raw_hosts.split(',') if h.strip()] + _base_hosts
else:
    ALLOWED_HOSTS = _base_hosts


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    "ninja",
    'ninja_extra',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
    'allauth.mfa',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',
    'channels',

    # Project apps
    "users",
    "sessions",
    "browsers",
    "workspaces",
    "cases",
    "notifications",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

SITE_ID = 1

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.oidc_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

# ─── Django Channels / Redis channel layer ────────────────────────────────────
_REDIS_URL = os.environ.get('REDIS_URL', 'redis://ovb_redis:6379/1')
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # Pass socket options inside the host dict so channels_redis
            # forwards them to the underlying redis-py connection pool.
            # socket_keepalive prevents Redis from dropping idle pub/sub
            # connections and eliminates the "Timeout reading from ovb_redis"
            # noise in the daphne logs.
            "hosts": [{
                "address": _REDIS_URL,
                "socket_connect_timeout": 5,
                "socket_timeout": 60,
                "socket_keepalive": True,
            }],
        },
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use SQLite only when explicitly requested (USE_SQLITE=1) or when no DB_HOST
# is configured.  In Docker Compose DB_HOST is always set, so PostgreSQL is
# used automatically there.  On the dev host you can keep SQLite by either
# setting USE_SQLITE=1 or simply not setting DB_HOST.
_use_sqlite = str_to_bool(os.environ.get('USE_SQLITE', '0')) or not os.environ.get('DB_HOST', '')

if _use_sqlite:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'ovb'),
            'USER': os.environ.get('DB_USER', 'ovb'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'ovb_postgres'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
            # Re-validate connection before reuse so stale sockets after a
            # Postgres restart or RDS failover don't surface as OperationalErrors.
            'CONN_HEALTH_CHECKS': True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CORS_ALLOW_CREDENTIALS = True

if CUSTOM_DOMAIN:
    _escaped = re.escape(CUSTOM_DOMAIN)
    if BASIC_MODE:
        # No reverse proxy — frontend on :3000, backend on :8000, plain HTTP.
        CORS_ALLOWED_ORIGIN_REGEXES = [
            rf"^http://[a-z0-9-]+\.{_escaped}(:[0-9]+)?$",
            rf"^http://{_escaped}(:[0-9]+)?$",
        ]
        CSRF_TRUSTED_ORIGINS = [
            f'http://{CUSTOM_DOMAIN}',
            f'http://{CUSTOM_DOMAIN}:3000',
            f'http://{CUSTOM_DOMAIN}:8000',
        ]
    else:
        # Behind a reverse proxy (Traefik / Nginx) — HTTPS only.
        CORS_ALLOWED_ORIGIN_REGEXES = [
            rf"^https://[a-z0-9-]+\.{_escaped}(:[0-9]+)?$",
            rf"^https://{_escaped}(:[0-9]+)?$",
        ]
        CSRF_TRUSTED_ORIGINS = [
            f'https://{CUSTOM_DOMAIN}',
            f'https://{CUSTOM_DOMAIN}:3000',
        ]
else:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ]
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ]

# Session Cookie Configuration for Cross-Domain Auth
SESSION_COOKIE_DOMAIN = f'.{CUSTOM_DOMAIN.split(":")[0]}' if CUSTOM_DOMAIN and not BASIC_MODE else None
SESSION_COOKIE_SAMESITE = 'Lax'
# Only mark cookies Secure when actually running over HTTPS. Controlled
# explicitly via env var so it works correctly regardless of DEBUG.
SESSION_COOKIE_SECURE = str_to_bool(os.environ.get('SESSION_COOKIE_SECURE', '0'))
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 1209600  # 2 weeks

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_LOGOUT_ON_GET = False  # require POST to prevent CSRF-triggered logout via GET
LOGIN_REDIRECT_URL = "/accounts/auth/gate/"
LOGIN_URL = '/accounts/login/'
ACCOUNT_SIGNUP_REDIRECT_URL = "/accounts/auth/gate/"
ACCOUNT_SIGNUP_ENABLED = str_to_bool(os.environ.get('ACCOUNT_ALLOW_SIGNUPS', 'True'))
ACCOUNT_ADAPTER = 'users.adapters.MyAccountAdapter'
APP_NAME = os.environ.get('APP_NAME', 'Example Name')

# OIDC/Social Account Configuration
# Configure via environment variables:
#   OIDC_PROVIDER_ID: A slug identifying your provider (used in the callback URL)
#   OIDC_CLIENT_ID: Client ID from your OIDC provider
#   OIDC_CLIENT_SECRET: Client secret from your OIDC provider
#   OIDC_SERVER_URL: Full URL to the .well-known/openid-configuration endpoint

OIDC_PROVIDER_TYPE = os.environ.get('OIDC_PROVIDER_ID', os.environ.get('OIDC_PROVIDER_TYPE', '')).lower()
OIDC_CLIENT_ID = os.environ.get('OIDC_CLIENT_ID', '')
OIDC_CLIENT_SECRET = os.environ.get('OIDC_CLIENT_SECRET', '')
OIDC_SERVER_URL = os.environ.get('OIDC_SERVER_URL', '')

OIDC_ENABLED = bool(OIDC_PROVIDER_TYPE and OIDC_CLIENT_ID and OIDC_CLIENT_SECRET and OIDC_SERVER_URL)

OIDC_APPS = []
if OIDC_ENABLED:
    OIDC_APPS = [
        {
            "provider_id": OIDC_PROVIDER_TYPE,
            "name": "SSO",
            "client_id": OIDC_CLIENT_ID,
            "secret": OIDC_CLIENT_SECRET,
            "settings": {
                "server_url": OIDC_SERVER_URL
            }
        }
    ]

SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": OIDC_APPS
    }
}

# if OIDC_PROVIDER_TYPE is not '' or OIDC_PROVIDER_TYPE is not None:
#     SOCIALACCOUNT_ONLY = True
# else:
#     SOCIALACCOUNT_ONLY = False

# Social Account Settings - Enable Email-Based Account Linking
SOCIALACCOUNT_ADAPTER = 'users.adapters.MySocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True  # Allow automatic signup via social login
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Don't force email verification for social accounts
SOCIALACCOUNT_QUERY_EMAIL = True  # Enable querying email from social provider
SOCIALACCOUNT_EMAIL_AUTHENTICATION=True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT=True

# Email Configuration
# In development: print emails to console
# In production: use SMTP
_email_enabled = str_to_bool(os.environ.get('EMAIL_ENABLED', '0'))

if DEBUG or not _email_enabled:
    EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = str_to_bool(os.environ.get('EMAIL_USE_TLS', '1'))
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Siene <noreply@example.com>')
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SECURE_SSL_REDIRECT = str_to_bool(os.environ.get('SECURE_SSL_REDIRECT', '0'))
CSRF_COOKIE_SECURE = str_to_bool(os.environ.get('CSRF_COOKIE_SECURE', '0'))

if not DEBUG:
    # HSTS (HTTP Strict Transport Security) — only meaningful with HTTPS
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = str_to_bool(os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', '0'))
    SECURE_HSTS_PRELOAD = str_to_bool(os.environ.get('SECURE_HSTS_PRELOAD', '0'))

    # Proxy SSL Header (for reverse proxy setups like Nginx/Traefik/Caddy)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True

    # Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    SECURE_REFERRER_POLICY = 'same-origin'

# ─── Celery ───────────────────────────────────────────────────────────────────
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', os.environ.get('REDIS_URL', 'redis://ovb_redis:6379/0'))
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', os.environ.get('REDIS_URL', 'redis://ovb_redis:6379/0'))
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_RESULT_EXTENDED = True
# Prefetch 1 message at a time so a crash doesn't silently drop queued work.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# Acknowledge only after the task completes — ensures requeue on worker crash.
CELERY_TASK_ACKS_LATE = True
# Use DatabaseScheduler; beat schedule is stored in the DB (via django-celery-beat)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ─── AWS / ECS ────────────────────────────────────────────────────────────────
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_REGION = os.environ.get('AWS_REGION', 'us-east-1')

SUBNET_ID = os.environ.get('SUBNET_ID', '')
SECURITY_GROUP_ID = os.environ.get('SECURITY_GROUP_ID', '')
ECR_REGISTRY = os.environ.get('ECR_REGISTRY', '')

# ─── Cloudflare ───────────────────────────────────────────────────────────────
CLOUDFLARE_API_TOKEN = os.environ.get('CF_Token', os.environ.get('CLOUDFLARE_API_TOKEN', ''))
CLOUDFLARE_ZONE_ID = os.environ.get('CF_Zone_ID', os.environ.get('CLOUDFLARE_ZONE_ID', ''))

# ─── Session / idle threshold ────────────────────────────────────────────────
DEFAULT_IDLE_THRESHOLD = os.environ.get('DEFAULT_IDLE_THRESHOLD', '10')

# ─── Fargate cost estimation ─────────────────────────────────────────────────
FARGATE_VCPU_PER_HOUR_USD = os.environ.get('FARGATE_VCPU_PER_HOUR_USD', '0.04048')
FARGATE_MEMORY_GB_PER_HOUR_USD = os.environ.get('FARGATE_MEMORY_GB_PER_HOUR_USD', '0.004445')
FARGATE_SPOT_DISCOUNT = os.environ.get('FARGATE_SPOT_DISCOUNT', '0.70')
# AWS charges $0.005/hr per public IPv4 address (since Feb 2024).
# Tasks use assignPublicIp: ENABLED, so every session incurs this.
# Set to '0' to disable if sessions are ever moved behind a NAT/load balancer.
PUBLIC_IPV4_PER_HOUR_USD = os.environ.get('PUBLIC_IPV4_PER_HOUR_USD', '0.005')

# ─── Browser path ─────────────────────────────────────────────────────────────
# Path to the directory containing browser image subdirectories (on the container)
VBROWSERS_PATH = os.environ.get('VBROWSERS_PATH', '/app/vbrowsers')

# ─── S3 / Storage ─────────────────────────────────────────────────────────────
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = AWS_REGION

# ─── S3 Files (persistent storage) ───────────────────────────────────────────
# File system ARN + ID provisioned by Terraform (modules/infrastructure/s3files.tf).
# Used to mount per-workspace access points at /config/Downloads in ECS tasks.
S3FILES_FILE_SYSTEM_ARN = os.environ.get('S3FILES_FILE_SYSTEM_ARN', '')
S3FILES_FILE_SYSTEM_ID = os.environ.get('S3FILES_FILE_SYSTEM_ID', '')
S3FILES_BUCKET_NAME = os.environ.get('S3FILES_BUCKET_NAME', '')


# ─── Logging ──────────────────────────────────────────────────────────────────
# Console logging is always active with a timestamped formatter.
#
# django.request  — emits ERROR for every HTTP 500 (full traceback included)
# django.security — emits ERROR for SuspiciousOperation and security violations
#
# In production (DEBUG=False, EMAIL_ENABLED=1) unhandled 500s are also mailed
# to ADMINS via AdminEmailHandler.  Set ADMINS in env or here to receive them:
#   DJANGO_ADMINS="Alice <alice@example.com>, Bob <bob@example.com>"
#
# Set LOGGER_ENABLED=1 to additionally write a debug.log file locally.

LOGGER_ENABLED = str_to_bool(os.environ.get('LOGGER_ENABLED', '0'))

# Parse ADMINS from env: "Name <email>, Name2 <email2>"
_admins_raw = os.environ.get('DJANGO_ADMINS', '')
ADMINS = []
if _admins_raw:
    import re as _re
    for _m in _re.finditer(r'([^<,]+?)\s*<([^>]+)>', _admins_raw):
        ADMINS.append((_m.group(1).strip(), _m.group(2).strip()))
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', os.environ.get('DEFAULT_FROM_EMAIL', 'django@localhost'))

_log_handlers = ['console']
_log_handler_config: dict = {
    'console': {
        'class': 'logging.StreamHandler',
        'formatter': 'verbose',
    },
}

if LOGGER_ENABLED:
    _log_handlers.append('file')
    _log_handler_config['file'] = {
        'class': 'logging.FileHandler',
        'filename': str(BASE_DIR / 'debug.log'),
        'formatter': 'verbose',
    }

# Wire AdminEmailHandler only when email is configured and we're in production.
# This sends an email to ADMINS on every unhandled 500 error.
_email_enabled = str_to_bool(os.environ.get('EMAIL_ENABLED', '0'))
if not DEBUG and _email_enabled and ADMINS:
    _log_handlers_errors = _log_handlers + ['mail_admins']
else:
    _log_handlers_errors = _log_handlers

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        **_log_handler_config,
        # Built-in handler — emails tracebacks to ADMINS. Only active when
        # email is configured; see _log_handlers_errors wiring above.
        'mail_admins': {
            'class': 'django.utils.log.AdminEmailHandler',
            'level': 'ERROR',
            'include_html': False,
        },
    },
    'root': {
        'handlers': _log_handlers,
        'level': 'WARNING',
    },
    'loggers': {
        # Django's request logger emits ERROR + full traceback for every 500.
        'django.request': {
            'handlers': _log_handlers_errors,
            'level': 'ERROR',
            'propagate': False,
        },
        # Security violations (SuspiciousOperation, bad Host header, etc.)
        'django.security': {
            'handlers': _log_handlers_errors,
            'level': 'ERROR',
            'propagate': False,
        },
        # Project app loggers — INFO and above
        'sessions':      {'handlers': _log_handlers, 'level': 'INFO', 'propagate': False},
        'browsers':      {'handlers': _log_handlers, 'level': 'INFO', 'propagate': False},
        'workspaces':    {'handlers': _log_handlers, 'level': 'INFO', 'propagate': False},
        'cases':         {'handlers': _log_handlers, 'level': 'INFO', 'propagate': False},
        'notifications': {'handlers': _log_handlers, 'level': 'INFO', 'propagate': False},
        'users':         {'handlers': _log_handlers, 'level': 'INFO', 'propagate': False},
    },
}