#!/usr/bin/with-contenv bash

# nginx Path
NGINX_CONFIG=/etc/nginx/sites-available/default
JS_FILE=/usr/share/selkies/www/assets/functions.js

UUID="${UUID}"
DEFAULT_IDLE_THRESHOLD="${DEFAULT_IDLE_THRESHOLD}"
CUSTOM_DOMAIN="${CUSTOM_DOMAIN}"

# user passed env vars
CPORT="${CUSTOM_PORT:-3000}"
CHPORT="${CUSTOM_HTTPS_PORT:-3001}"
CWS="${CUSTOM_WS_PORT:-8082}"
CUSER="${CUSTOM_USER:-abc}"
SFOLDER="${SUBFOLDER:-/}"

ADD_HEADERS="yes"

if [[ "$ADD_HEADERS" == "yes" ]]; then
    NGINX_VAR='add_header              Permissions-Policy "microphone=(self '"${CUSTOM_DOMAIN}"'), camera=(self '"${CUSTOM_DOMAIN}"'), speaker=(self '"${CUSTOM_DOMAIN}"'), autoplay=(self '"${CUSTOM_DOMAIN}"'), fullscreen=(self '"${CUSTOM_DOMAIN}"'), clipboard-read=(self '"${CUSTOM_DOMAIN}"'), clipboard-write=(self '"${CUSTOM_DOMAIN}"')";'
else
    NGINX_VAR='add_header              Permissions-Policy "microphone=*, camera=*, speaker=*, autoplay=*, fullscreen=*, clipboard-read=*, clipboard-write=*";'
fi

# create self signed cert
if [ ! -f "/config/ssl/cert.pem" ]; then
  mkdir -p /config/ssl
  openssl req -new -x509 \
    -days 3650 -nodes \
    -out /config/ssl/cert.pem \
    -keyout /config/ssl/cert.key \
    -subj "/C=US/ST=IL/L=Chicago/O=vBrowser.io/OU=vBrowser Server/CN=*"
  chmod 600 /config/ssl/cert.key
  chown -R abc:abc /config/ssl
fi

# modify nginx config
cp /defaults/default.conf ${NGINX_CONFIG}
sed -i "s/3000/$CPORT/g" ${NGINX_CONFIG}
sed -i "s/3001/$CHPORT/g" ${NGINX_CONFIG}
sed -i "s|{{UUID}}|$UUID|g" $NGINX_CONFIG
sed -i "s/CWS/$CWS/g" ${NGINX_CONFIG}
sed -i "s|SUBFOLDER|$SFOLDER|g" ${NGINX_CONFIG}
sed -i "s|REPLACE_HOME|$HOME|g" ${NGINX_CONFIG}
sed -i "s|{{UUID}}|$UUID|g" $JS_FILE
sed -i "s|{{DEFAULT_IDLE_THRESHOLD}}|$DEFAULT_IDLE_THRESHOLD|g" $JS_FILE
sed -i "s|{{CUSTOM_DOMAIN}}|$CUSTOM_DOMAIN|g" $JS_FILE
sed -i "s|NGINX_VAR|${NGINX_VAR}|g" "$NGINX_CONFIG"
s6-setuidgid abc mkdir -p $HOME/Desktop
if [ ! -z ${DISABLE_IPV6+x} ]; then
  sed -i '/listen \[::\]/d' ${NGINX_CONFIG}
fi
if [ ! -z ${PASSWORD+x} ]; then
  printf "${CUSER}:$(openssl passwd -apr1 ${PASSWORD})\n" > /etc/nginx/.htpasswd
  sed -i 's/#//g' ${NGINX_CONFIG}
fi
if [ ! -z ${DEV_MODE+x} ]; then
  sed -i \
    -e 's:location / {:location /null {:g' \
    -e 's:location /devmode:location /:g' \
    ${NGINX_CONFIG}
fi

# copy favicon
cp \
  /usr/share/selkies/www/icon.png \
  /usr/share/selkies/www/favicon.ico
