#!/bin/bash

BIN=/usr/bin/chromium

# Cleanup
if ! pgrep chromium > /dev/null; then
  rm -f $HOME/.config/chromium/Singleton*
fi

# Run normally on privved containers or modified on non-privileged ones
if grep -q 'Seccomp:.0' /proc/1/status; then
  ${BIN} \
  --ignore-gpu-blocklist \
  --no-first-run \
  --password-store=basic \
  --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
  --start-maximized \
  --user-data-dir \
   "$@" $FF_OPEN_URL > /dev/null 2>&1 &  # Run Chromium in the background
else
  ${BIN} \
  --ignore-gpu-blocklist \
  --no-first-run \
  --no-sandbox \
  --password-store=basic \
  --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
  --start-maximized \
  --test-type \
  --user-data-dir \
   "$@" $FF_OPEN_URL > /dev/null 2>&1 &  # Run Chromium in the background
fi

PROCESS_NAME="chromium"


