# Generated by Django 6.0.6 on 2026-07-13 17:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('port', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Port')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Format: YYYY-MM-DD HH:MM:SS', null=True, verbose_name='Date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('private_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Private IP Address')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP Address')),
                ('subdomain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subdomain')),
                ('session_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session Token')),
                ('container_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Container URL')),
                ('task_arn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Task ARN')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('sg_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='SG ID')),
                ('capacity_provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacity Provider')),
                ('category', models.CharField(blank=True, max_length=10, null=True, verbose_name='Category')),
                ('vcpu', models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=4)),
                ('memory_gb', models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=6)),
                ('session_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='cases.case')),
                ('tags', models.ManyToManyField(blank=True, related_name='containers', to='cases.tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='OpenContainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_uuid', models.CharField(max_length=255, null=True, verbose_name='UUID')),
                ('last_ping_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vbsessions.container')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='session_logs/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vbsessions.container')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('mode', models.CharField(choices=[('view', 'View only'), ('control', 'Full control')], default='view', max_length=10)),
                ('workspace_only', models.BooleanField(default=False, help_text='If true, only workspace members can use this link')),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('allowed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_share_links', to=settings.AUTH_USER_MODEL)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='vbsessions.container')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
