# Generated by Django 6.0.7 on 2026-07-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbsessions', '0004_trafficevent_flagged'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trafficevent',
            new_name='vbsessions__contain_350152_idx',
            old_name='vbsessions_traffice_contain_idx',
        ),
        migrations.RenameIndex(
            model_name='trafficevent',
            new_name='vbsessions__contain_a5f14f_idx',
            old_name='vbsessions__contain_flagged_idx',
        ),
    ]
