# Generated by Django 6.0.6 on 2026-07-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbsessions', '0007_alter_opencontainers_last_ping_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='persistent_storage',
            field=models.BooleanField(default=False, help_text='Whether persistent S3 storage was mounted for this session', verbose_name='Persistent Storage'),
        ),
    ]
