# Generated by Django 6.0.6 on 2026-07-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('vbsessions', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionnote',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='vbsessions.container'),
        ),
        migrations.AddField(
            model_name='tag',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='workspaces.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('workspace', 'name')},
        ),
    ]
