#!/bin/bash

# Default folder
if [ ! -f $HOME/lsio ]; then
  mkdir $HOME/lsio
fi

# Start app
/app/Browser/mullvadbrowser-lsio

PROCESS_NAME="mullvadbrowser-lsio"
API_URL="https://$CUSTOM_DOMAIN/close_session/$UUID"

while true; do
    if ! pgrep -f "$PROCESS_NAME" > /dev/null; then
        echo "Process $PROCESS_NAME not found. Sending API request."
        curl -X POST -H "Content-Type: application/json" "$API_URL"
        break
    fi
    sleep 10  # Check every 10 seconds
done
