# Generated by Django 6.0.7 on 2026-07-13 21:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_extendprofile_userlimit_apikey_sitesettings_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
