# Generated by Django 6.0.7 on 2026-07-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_apikey_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mfa_suspended_user_ids',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
