# Generated by Django 6.0.6 on 2026-07-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_sitesettings_feature_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='browser_memory_gb',
            field=models.DecimalField(decimal_places=2, default='2.0', help_text='RAM in GB for standard browser sessions (e.g. 0.5, 1.0, 2.0).', max_digits=6),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='browser_vcpu',
            field=models.DecimalField(decimal_places=2, default='0.5', help_text='vCPU allocation for standard browser sessions (e.g. 0.25, 0.5, 1.0).', max_digits=4),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='os_memory_gb',
            field=models.DecimalField(decimal_places=2, default='4.0', help_text='RAM in GB for OS-based sessions (Kali, Ubuntu, Alpine).', max_digits=6),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='os_vcpu',
            field=models.DecimalField(decimal_places=2, default='2.0', help_text='vCPU allocation for OS-based sessions (Kali, Ubuntu, Alpine).', max_digits=4),
        ),
    ]
