# Generated by Django 6.0.6 on 2026-07-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_sitesettings_resource_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_persistent_storage',
            field=models.BooleanField(default=False, help_text='When enabled, workspace admins may allow members to use persistent S3 storage.'),
        ),
    ]
