#!/bin/bash

vivaldi \
  --start-maximized \
  --disable-dev-shm-usage \
  --ignore-gpu-blocklist \
  --no-first-run \
  --password-store=basic \
  --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
  --start-maximized \
  --user-data-dir \
  --url $FF_OPEN_URL \
   "$@"  > /dev/null 2>&1

PROCESS_NAME="vivaldi"






